### ISSUE TITLE
Error during github install

### ISSUE THREAD

**Issue by ammaraziz** [jennahamlin/Tinsel#21]
**Describe the bug**
Very cool R package. I am currently testing and came across an installation issue. I am sure others will have similar issues. 

Current recommended method of installation uses `devtools::install_github`. I think if the github repo is downloaded too many times it triggers a requirement for authentication, which means an access token is needed.

```
> devtools::install_github("jennahamlin/tinselR@release-V0.0.0.90")
Using github PAT from envvar GITHUB_PAT
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 59/60
  Rate limit reset at: 2022-08-31 03:48:56 UTC
```

**Expected behavior**
Installation

**Additional context**
I guess if this package gets published to bioconductor this won't become an issue. Until then, can I recommend the inclusion of some instructions for creating a PAT or alternatives download methods. 

For creating a PAT I found these instructions helpful:
https://gist.github.com/Z3tt/3dab3535007acf108391649766409421

```
usethis::use_git_config(user.name = "YourName", user.email = "your@mail.com")
usethis::create_github_token() 
credentials::set_github_pat("YourPAT")
usethis::edit_r_environ()
```

**Comment by jennahamlin** [comment]
Hi Ammar-

Glad you found a solution and thank you for providing a link to something that was helpful to you.
